version: "3.8"

services:
  bot:
    build: .
    image: ghcr.io/hiizun/dancefloor:latest
    container_name: dancefloor
    restart: on-failure
    environment:
      - TOKEN=${TOKEN}
      - GUILD_ID=${GUILD_ID}
      - APPLICATION_ID=${APPLICATION_ID}
      - OWNERS=${OWNERS}
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}