name: Docker Image CI

on:
  push:
    branches: [ "master", "full-recast-djs-v14" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push amd64 & arm64 Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform=linux/amd64,linux/arm64 -t ghcr.io/hiizun/dancefloor:latest -f Dockerfile --push .
